
# Font stuffs
font_family FiraCode Nerd Font
font_size 13
disable_ligatures never

# Visual
window_padding_width 7
hide_window_decorations titlebar-only

# Colors / Backgroud
background_opacity 0.92
# Rosé Pine Moon
include current-theme.conf

# Funny
enable_audio_bell yes
bell_path "/Users/lukewharton/.config/sounds/vine-boom.mp3"
