
# Font stuffs
font_family FiraCode Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
symbol_map U+E000-U+F1AF0 FiraCode Nerd Font
font_size 12.5
disable_ligatures never

# Visual
window_margin_width 1
hide_window_decorations titlebar-only


# Colors / Backgroud
background_opacity 0.92

# Funny
enable_audio_bell yes
bell_path sounds/vine-boom.wav

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME
